config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  match "/404", to: "errors#not_found", via: :all
  match "/500", to: "errors#internal_server_error", via: :all
  root to: 'artworks#index'
  get '/profile', to: 'pages#profile'
  get '/share/:artwork_id', to: 'pages#share', as: 'share'
  post '/mail_request/:artwork_id', to: 'mail_requests#invite_externals', as: 'invite_externals'
  get '/brandguidelines', to: 'pages#brandguidelines'
  get '/landing', to: 'pages#landing'
  get '/users/:id/friends', to: 'users#friends', as: 'friends'
  get '/discover', to: 'artworks#discover'
  get '/artists', to: 'users#index'
  get '/support', to: 'pages#support'
  post '/artworks/:artwork_id/comments/feed', to: 'comments#create_index', as: 'create_comments_index'
  patch 'friendships/:id/accept', to: 'friendships#accept', as: 'accept_friendship'
  patch 'friendships/:id/decline', to: 'friendships#decline', as: 'decline_friendship'
  resources :users, only: :show do
    resources :friendships, only: :create
  end
  resources :artworks, only: [:index, :new, :create, :show] do
    resources :comments, only: [:create]
  end

  get 'card/:id', to: 'comments#card', as: :card

  # Please do NOT delete (it will break the home page)
  # post '/banana', to: 'comments#create_index', as: :create_comments_index
  # ⚠️⚠️⚠️

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/artwork.rb
class Artwork < ApplicationRecord
  belongs_to :user
  has_many :feedback_requests, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many_attached :photos

  validates :title, presence: true
  validates :description, presence: true
  validates :description, length: { minimum: 10 }
end

app/controllers/artworks_controller.rb
class ArtworksController < ApplicationController
  before_action :set_artwork, only: [:show, :destroy]
  before_action :set_user_ids, only: [:create]
  attr_reader :privacy
  # skip_before_action :authenticate_user!, only: [ :index ]

  def index
    @comment = Comment.new
    all_artworks = Artwork.where(privacy: false).order(created_at: :desc)
    @requested_feedback_artworks = Artwork.joins(:feedback_requests).where(feedback_requests: { user: current_user }).order(created_at: :desc)
    @public_artworks = all_artworks - @requested_feedback_artworks
    @created_comment = nil
    if params[:new_comment_id]
      @created_comment = Comment.find(params[:new_comment_id])
    end
  end

  def show
    authorize @artwork unless params[:external]

    @comment = Comment.new
    @general_comments_i, @marked_comments_i = @artwork.comments.partition { |comment| comment.x_offset.nil? || comment.y_offset.nil? }
    @general_comments = @general_comments_i.sort_by!(&:created_at).reverse
    @marked_comments = @marked_comments_i.sort_by(&:created_at).reverse
  end

  def discover
    @public_artworks = Artwork.where(privacy: false).order(created_at: :desc)
  end

  def new
    @artwork = Artwork.new
  end
  
  def create
    @artwork = Artwork.new(artwork_params)
    @artwork.user = current_user
    # setting the version to 1; how can we change the code if we want to implement later versions?
    @artwork.version = 1
    if @artwork.save
      @user_ids&.each do |id| 
        FeedbackRequest.create(user_id: id, artwork: @artwork)
      end
      redirect_to share_path(artwork_id: @artwork.id)
    else
      render :new
    end
  end

  def destroy
    @artwork.destroy
    redirect_to artworks_path
  end

  private

  def set_user_ids
    @user_ids = params[:artwork][:user_id]
  end

  def set_artwork
    @artwork = Artwork.find(params[:id])
  end

  def artwork_params
    params.require(:artwork).permit(:title, :description, :version, :privacy, :request, photos: [])
  end
end

app/views/artworks/_artworks_card.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-sm-9 mt-5">
      <a href="<%= artwork_path(artwork) %>" class="hover-img-container">
        <% if artwork.photos.present? %>
          <%= cl_image_tag artwork.photos.first.key, class: 'center-img', alt: "artwork", id: "artwork-image-#{artwork.id}" %>
        <% end %>
        <div class="overlay">
          @<%= artwork.user.username %><br>
          <%= artwork.title %>
        </div>
      </a>
    </div>
  </div>

  <div id="comments_for_<%= artwork.id %>" class="row justify-content-center">
    <div class="col-sm-9">
      <div class="container d-flex p-0">
        <% if artwork.id == @created_comment&.artwork&.id %>
          <% if current_user.photo.attached? %>
             <%= cl_image_tag current_user.photo.key, class: 'profile mr-2 mt-2' %>
          <% end %>
          <div class="text-comment mt-2">
            <em><%= @created_comment.content %></em>
          </div>
        <% end %>
      </div>
    </div>
  </div>

  <div class="row justify-content-center">
    <div class="col-sm-9 my-2">
      <div class="container d-flex p-0">
        <% if current_user.photo.attached? %>
          <%= cl_image_tag current_user.photo.key, class: 'profile mr-2' %>
        <% end %>
        <%= simple_form_for [artwork, @comment], url: create_comments_index_path(artwork), method: :post, remote: true, data: { turbolinks: false }, html: { class: 'd-flex flex-column flex-grow-1', id: "new_comment_#{artwork.id}" } do |f| %>
          <%= f.input :content, input_html: { class: 'flex-grow-1, small-text', id: "comment_content_#{artwork.id}" }, placeholder: 'What would you like to say about this piece?', label: false %>
          <div class="button-wrapper-feedback">
            <%= f.submit value: "Send feedback", class: 'btn-send-feedback justify-content-center mb-3 send-feedback', 'data-disable-with' => "Send feedback" %>
            <a href="#" class="btn-shadow-feedback">Send feedback</a>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/artworks/_comment_form.html.erb
<%= simple_form_for [@artwork, @comment], html: { class: 'd-flex flex-column flex-grow-1' } do |f| %>
  <%= f.input :content, input_html: { class: 'flex-grow-1 comment-field' }, placeholder: 'What would you like to say about this piece?', label: false %>
  <div class="button-wrapper-feedback">
    <%= f.submit value: "Send feedback", class: 'btn-send-feedback justify-content-center mb-3 send-feedback', 'data-disable-with' => "Send feedback" %>
    <a href="#" class="btn-shadow-feedback">Send feedback</a>
  </div>
  <%= hidden_field_tag :coming_from, action_name %>
  <%= f.input :x_offset, as: :hidden %>
  <%= f.input :y_offset, as: :hidden %>
<% end %>

app/views/artworks/_general_comments.html.erb
  <% @general_comments.each do |comment| %> 
      <div class="d-flex mb-3">
        <%= cl_image_tag comment.user.photo.key, class: 'profile mr-2' %>
        <p class="comment ml-3"><%= comment.content %></p>
      </div>
  <% end %>

app/views/artworks/_marked_comments.html.erb
  <% @marked_comments.each do |comment| %> 
    <div class="d-flex mb-3">
      <%= cl_image_tag comment.user.photo.key, class: 'profile mr-2' %>
      <p class="comment ml-3"><%= comment.content %></p>
    </div>
  <% end %>

app/views/artworks/_popover_comment.html.erb
<div data-popover-target="card" class="d-flex feedback-popover">
  <%= cl_image_tag comment.user.photo.key, class: 'profile-comment-sm ml-2' %>
  <div class="p-2 my-2">
    <%= comment.content %>
  </div>
</div>

app/views/artworks/discover.html.erb
<div class="container mt-5">
  <h1 class="center-headers" > Discover Artworks </h1>
    <div class="grid">
      <div class="gutter-size"></div>
      <% @public_artworks.each do |artwork| %>
        <% artwork.photos.each do |photo| %>
          <div class="grid-item">
            <%= cl_image_tag photo.key, class: "w-100" %>

          <a href="<%= artwork_path(artwork) %>" class="hover-img-container-2">

            <div class="overlay">
              @<%= artwork.user.username %><br>
              <%= artwork.title %>
            </div>
          </a>
          </div>
        <% end %>
      <% end %>
    </div>
</div>

app/views/artworks/index.html.erb
<div>
  <i id="myBtn" class="bi bi-arrow-up"></i>
<%#   <button id="myBtn" class="fas fa-sort-down" title="Go to top"><%# Top %><%# </button> %>
</div>
<div class="mb-5" <%# id="scroll-button" %>>
  <% @requested_feedback_artworks.each do |artwork| %>
    <%= render "artworks_card", artwork: artwork, comment: @comment %>
  <% end %>

  <% @public_artworks.each do |artwork| %>
    <%= render "artworks_card", artwork: artwork, comment: @comment %>
  <% end %>
<%#   <a id="down" href="#scroll-button"><i id="down-arrow" class="fas fa-sort-down"></i></a> %>
</div>

app/views/artworks/new.html.erb
<section>
  <%= simple_form_for @artwork, html: { class: "upload d-flex justify-content-evenly"} do |f| %>
    <div class="col-4 col-md-4 p-5">
      <div class='scroll-bar-wrapper'> 
        <div class='scroll-bar'> </div>
      </div>
      <div class="mb-4 flex-wrap hidden-scrollbar" id="artwork-images">
        <i class="fas fa-plus fa-4x" id="cross"></i>
      </div>
      <%  %>
      <div class="btn-wrapper-select">
        <%= f.input :photos, as: :file, input_html: { multiple: true, class: 'd-none' }, label_html: { class: 'btn-select'}, label: 'Select artwork' %>
        <a href="#" class="btn-shadow-select">Create artwork</a>
      </div>
    </div>
    <div class="col-8 col-md-8 p-5">
      <div class="form-input" sytle="border-radius: 4px">
        <%= f.input :title, label: 'Title', placeholder: "Title" %>
        <%= f.input :description, label: 'Description', placeholder: "What is your work about?" %>
        <%= f.input :request, placeholder: "Is there any specific feedback you are looking for?" %>
      </div>
      <div class="row feedbacker-input">
        <%= simple_fields_for :feedback_requests do |fr|%>
        <%= f.input :user_id,
          collection: current_user.friends.map { |user| [ "#{user.first_name} #{user.last_name}", user.id] },
          value: @artwork.feedback_requests.map { |fr| fr.user.id },
          include_hidden: false,
          label: "Select feedbackers",
          wrapper_html: { class: 'w-100' },
          input_html: {
          data: {
            controller: "searchable-select",
            searchable_select_target: 'input'
          },
          multiple: true
          } 
          %>
        <% end %>
      </div>
      <%# add external via email through an popup with button below (Add external) %>
      <%# <div id="feedbacker-selection"></div> %>
      <div class="d-flex flex-row-reverse submit-input mt-4 align-items-center">
      <%# change the button to button primary with hover effect %>
        <!-- Button trigger modal -->
          <div class="btn-wrapper-upload btn-no-margin">
            <button type="button" class="btn-upload" data-toggle="modal" data-target="#exampleModalCenter">
              Upload artwork
            </button>
            <a href="#" class="btn-shadow-upload">Upload your art</a>
          </div>
        <!-- <button type="button" class="submit-artwork ml-5" data-toggle="modal" data-target="#exampleModalCenter">
          Create artwork
        </button> -->
        <%# <%= f.submit class: 'submit-artwork ml-5',  data: { toggle: 'modal', target: '#exampleModalCenter' } %>
        <!-- Modal -->
        <div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
          <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
              <div class="modal-header">
                <h5 class="modal-title" style="font-size: 16px" id="exampleModalLongTitle">Confirm Upload</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                </button>
              </div>
              <div class="modal-body text-center">
                <p>Would you like to create this post?</p>
              </div>
              <div class="modal-footer justify-content-center">
                <div class="button-wrapper-create mt-2">
                   <%= f.submit value: "Create artwork", class: 'btn-create justify-content-center mb-3', 'data-disable-with' => "Create artwork" %>
                   <a href="#" class="btn-shadow-create">Create artwork</a>
                 </div>
              </div>
            </div>
          </div>
        </div>
        <%= f.input :privacy, as: :boolean, label_html: { class: "toggle-label mt-3 mr-4" }, input_html: { class: "toggle"}, label: 'Private' %>
      </div>
    </div>
  <% end %>
</section>

<%# in the show view insert following line to display image: cl_image_tag photo.key, height: 300, width: 400, crop: :fill %>

app/views/artworks/show.html.erb
<% if policy(@artwork).show? || params[:external] %>
  <div class="container">
    <div class="col-m-12">
      <div class="d-flex mt-5 mb-3">
        <% if @artwork.user.photo.key %>
          <%= cl_image_tag @artwork.user.photo.key, width: 62, height: 62, crop: :thumb, gravity: :face, class: 'profile mr-2' %>
        <% end %>
        <div class="flex-grow-1 mx-3 top-description">
          <h1><%= @artwork.title %> </h1>
          <p>@<%= link_to @artwork.user.username, user_path(@artwork.user) %></p>
        </div>
        <% unless @artwork.user.friends.include?(current_user) || current_user == @artwork.user %>
          <div class="btn-wrapper-follow">
            <%= link_to 'Follow', user_friendships_path(@artwork.user), class: 'btn-follow', method: :post %>
            <a href="#" class="btn-shadow-follow">Follow</a>
          </div>
        <% end %>
      </div>
      <div class="row m-auto" id="show-row">
        <p class="col-sm-10 m-auto pt-3"><%= @artwork.description %></p>
        <p class="col-sm-10 m-auto pt-1"><strong class="mr-2">Request details: </strong><%= @artwork.request %></p>
      </div>
      <div class="artwork-seperator col-sm-10 m-auto mt-3">
        <div class="align-self-end text-end pr-1">
          <p class="privacy-show m-0 mb-1">
            <% if @artwork.privacy == false %>Public
            <% elsif @artwork.privacy == true %>Private
            <% end %>
          </p>
        </div>
      </div>

      <div class="d-flex justify-content-center mt-4">
        <% @artwork.photos.each do |image|%>
          <div class="image-wrapper">
            <%= cl_image_tag image.key, class: 'mb-3', :alt => "artwork", id: "artwork", style: 'object-fit: cover; max-width: 920px; max-height: 80vh' %>
            <% @marked_comments.each do |comment| %>
              <div
                data-controller="popover"
                data-popover-url-value="<%= card_path(comment.id) %>"
              >
                <a data-action="mouseover->popover#show mouseout->popover#hide">
                  <i class="far fa-dot-circle marker artwork route-pin", style="top: <%= comment.y_offset%>px; left: <%=comment.x_offset%>px"></i>
                </a>
              </div>
            <% end %>
          </div>
        <% end %>
      </div>

      <div class="row justify-content-center">
        <div class="col-sm-10 my-2">
          <div class="container d-flex p-0">
            <% if current_user.photo.attached? %>
              <%= cl_image_tag current_user.photo.key, width: 62, height: 62, crop: :thumb, gravity: :face, class: 'profile mr-2' %>
            <% end %>
            <%= render  "comment_form" %>
          </div>
        </div>
      </div>

      <div class="row justify-content-center">
        <div class="col-sm-10 my-2">
          <ul class="nav justify-content-center nav-tabs mt-3" id="myTab" role="tablist">
            <li class="nav-item" role="presentation">
              <button class="nav-link comment-tabs active" id="general_comments-tab" data-bs-toggle="tab" data-bs-target="#general_comments" type="button" role="tab" aria-controls="general_comments" aria-selected="true">General comments</button>
            </li>
            <li class="nav-item" role="presentation">
              <button class="nav-link comment-tabs" id="marked_comments-tab" data-bs-toggle="tab" data-bs-target="#marked_comments" type="button" role="tab" aria-controls="marked_comments" aria-selected="false">Marked comments</button>
            </li>
          </ul>
          <div class="tab-content mb-5 p-5 comment-area" id="myTabContent">
            <div class="tab-pane fade show active" id="general_comments" role="tabpanel" aria-labelledby="general_comments-tab">
              <%= render  "general_comments" %>
            </div>
            <div class="tab-pane fade" id="marked_comments" role="tabpanel" aria-labelledby="marked_comments-tab">
              <%= render  "marked_comments" %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>