config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  match "/404", to: "errors#not_found", via: :all
  match "/500", to: "errors#internal_server_error", via: :all
  root to: 'artworks#index'
  get '/profile', to: 'pages#profile'
  get '/share/:artwork_id', to: 'pages#share', as: 'share'
  post '/mail_request/:artwork_id', to: 'mail_requests#invite_externals', as: 'invite_externals'
  get '/brandguidelines', to: 'pages#brandguidelines'
  get '/landing', to: 'pages#landing'
  get '/users/:id/friends', to: 'users#friends', as: 'friends'
  get '/discover', to: 'artworks#discover'
  get '/artists', to: 'users#index'
  get '/support', to: 'pages#support'
  post '/artworks/:artwork_id/comments/feed', to: 'comments#create_index', as: 'create_comments_index'
  patch 'friendships/:id/accept', to: 'friendships#accept', as: 'accept_friendship'
  patch 'friendships/:id/decline', to: 'friendships#decline', as: 'decline_friendship'
  resources :users, only: :show do
    resources :friendships, only: :create
  end
  resources :artworks, only: [:index, :new, :create, :show] do
    resources :comments, only: [:create]
  end

  get 'card/:id', to: 'comments#card', as: :card

  # Please do NOT delete (it will break the home page)
  # post '/banana', to: 'comments#create_index', as: :create_comments_index
  # ⚠️⚠️⚠️

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :comments, dependent: :destroy
  has_many :artworks
  has_many :feedback_requests
  has_many :friendships
  has_many :friendships_as_asker, class_name: "Friendship", foreign_key: :asker_id
  has_many :friendships_as_receiver, class_name: "Friendship", foreign_key: :receiver_id
  has_one_attached :photo
  has_many :pending_friendships, -> { where status: 'pending' }, class_name: 'Friendship', foreign_key: :receiver_id

  validates :username, presence: true
  validates :username, uniqueness: true
  validates :first_name, presence: true
  validates :last_name, presence: true

  def friends
    friends_one = Friendship.where(asker: self, status: 'accepted').map { |friendship| User.find(friendship.receiver_id)}
    friends_two = Friendship.where(receiver: self, status: 'accepted').map { |friendship| User.find(friendship.asker_id)}
    friends_one + friends_two
  end

  def send_invitation(user_id)
    Friendship.create!(asker: self, receiver_id: user_id, status: 'pending')
  end

  def pending_invitations
    pending_friendships
  end

  def public_artworks
    artworks.where(privacy: false)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
    f_requests = Artwork.joins(:feedback_requests).where(feedback_requests: { user: current_user }, artworks: { privacy: true, user: @user })
    # pictures = public_artworks && artwork where Feedbackrequest
    # exists with user_id === current_user
    # filter user_ids array for user === current user and display artwork
    public_pics = @user.public_artworks
    # shared_pics =
    @all_artworks = public_pics + f_requests
  end

  def friends
  end

  def index
    @users = User.all
  end
end

app/views/users/friends.html.erb
<div class="container">
  <h1 class="text-center mt-3">Your Friends</h1>

  <% if current_user.friends.any? %>
    <div class="d-flex justify-content-center mt-3 flex-wrap mb-3">
      <% current_user.friends.each do |friend| %>
        <div class="d-flex flex-column text-center m-1 mr-3 ml-3">
          <a href="/users/<%= friend.id %>">
            <%= cl_image_tag friend.photo.key, width: 120, height: 120, crop: :thumb, gravity: :face, class: 'profile-friends' %>
          </a>
          <%= link_to "@" + friend.username, user_path(friend.id), id:'dark-link'%>
        </div>
      <% end %>
    </div>
  <% end %>

  <% if current_user.pending_invitations.any? %>
    <h3 class="text-center mt-3">Pending Friend Requests</h3>
    <% current_user.pending_invitations.each do |request| %>
      <div class="d-flex mt-3">
        <%= cl_image_tag User.find(request.asker_id).photo.key, width: 120, height: 120, crop: :thumb, gravity: :face, class: 'profile-friends' %>
        <div class="container ml-3 top-description d-flex align-items-center">
          @<%= link_to User.find(request.asker_id).username, user_path(request.asker_id), id:'dark-link' %> <br>
        </div>
        <div class="container ml-3 top-description d-flex align-items-center">
          <%= link_to 'Accept', accept_friendship_path(request), class: 'button-primary', method: :patch %>
          <%= link_to 'Decline', decline_friendship_path(request), class: 'button-secondary', method: :patch %>
        </div>
      </div>
    <% end %>
  <% end %>

  <% if current_user.friends.empty? %>
    <div class="text-center mt-auto mt-5">
      <h3 class="mt-5">You don't have any friends yet.</h3>
      <p>Check out other <%= link_to 'Artists', artists_path, class:'friends' %> you can follow.</p>
    </div>
  <% end %>
</div>

app/views/users/index.html.erb
<div class="container mt-5">
  <h1 class="center-headers" > Discover Artists </h1>
    <div class="user-index-grid">
      <% @users.shuffle.each do |user| %>
          <div class="user-index-image-container">

              <% if current_user == user %>
                <a href="<%= profile_path %>" class="hover-img-container-3">
              <% else %>
              <a href="<%= user_path(user) %>" class="hover-img-container-3">

              <% end %>
            <% if user.photo.attached? %>
              <%= cl_image_tag(user.photo.key, gravity: :face, crop: :thumb, height: 250, width: 250, class: "user-index-image") %>
            <% elsif user.avatar %>
              <img src=<%= user.avatar %> alt="avatar" class="user-index-image">
            <% else %>
            <p>Picture not found</p>
            <% end %>

              <div class="overlay">
                @<%= user.username %><br>
                <%= user.artworks.length %> Artworks uploaded
              </div>
            </a>

          </div>
      <% end %>
    </div>
</div>

app/views/users/show.html.erb
<div class="container mt-5">
  <!-- Content here -->
  <div class="d-flex flex-row bd-highlight mb-3 justify-content-between">
    <div class="d-flex">
      <% if @user.photo.attached? %>
        <%= cl_image_tag @user.photo.key, class:"profile-home", height: 300, width: 400, crop: :fill %>
      <% else %>
        <img src="https://source.unsplash.com/EdAVNRvUVH4/150x150" class="img-thumbnail" alt="Profile Picture ">
      <% end %>
      <!-- <img src="https://source.unsplash.com/X6Uj51n5CE8/150x150" class="img-thumbnail" alt="Profile Picture"> -->
    </div>
    <div class="d-flex flex-column bd-highlight flex-grow-1 ml-2">
      <div><h1><i>@<%= @user.username %></i></h1></div>
      <div>👾 <%= @user.first_name %> <%= @user.last_name %></div>
      <div>📍 <%= @user.location %></div>
    </div>

    <div class="d-flex align-items-center">
      <% if Friendship.where(asker_id: current_user.id, receiver_id: @user.id, status: 'pending').any? %>
        <h6>Pending friendship request.</h6>
      <% else %>
        <% unless current_user.friends.include?(@user) || current_user == @user %>
          <div>
            <%= link_to 'Follow', user_friendships_path(params[:id]), class: 'button-primary', method: :post %>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>

 <div class="d-flex justify-content-center">
    <p class="centered-content"><%= @user.bio %></p>
  </div>


<!--Grid row-->
  <div class="grid">
    <div class="gutter-size"></div>
    <%# @user.public_artworks.each do |artwork| %>
      <% @all_artworks.each do |artwork| %>
      <% artwork.photos.each do |photo| %>
      <div class="grid-item">
      <%= cl_image_tag photo.key, class: "w-100" %>

        <a href="<%= artwork_path(artwork) %>" class="hover-img-container-2">
          <div class="overlay">
            <%= artwork.title %>
          </div>
        </a>
      </div>
      <% end %>
      <% end %>
    </div>
</div>