config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  match "/404", to: "errors#not_found", via: :all
  match "/500", to: "errors#internal_server_error", via: :all
  root to: 'artworks#index'
  get '/profile', to: 'pages#profile'
  get '/share/:artwork_id', to: 'pages#share', as: 'share'
  post '/mail_request/:artwork_id', to: 'mail_requests#invite_externals', as: 'invite_externals'
  get '/brandguidelines', to: 'pages#brandguidelines'
  get '/landing', to: 'pages#landing'
  get '/users/:id/friends', to: 'users#friends', as: 'friends'
  get '/discover', to: 'artworks#discover'
  get '/artists', to: 'users#index'
  get '/support', to: 'pages#support'
  post '/artworks/:artwork_id/comments/feed', to: 'comments#create_index', as: 'create_comments_index'
  patch 'friendships/:id/accept', to: 'friendships#accept', as: 'accept_friendship'
  patch 'friendships/:id/decline', to: 'friendships#decline', as: 'decline_friendship'
  resources :users, only: :show do
    resources :friendships, only: :create
  end
  resources :artworks, only: [:index, :new, :create, :show] do
    resources :comments, only: [:create]
  end

  get 'card/:id', to: 'comments#card', as: :card

  # Please do NOT delete (it will break the home page)
  # post '/banana', to: 'comments#create_index', as: :create_comments_index
  # ⚠️⚠️⚠️

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer text-center">
  <div class="footer-links mt-3">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-helpers mt-3">
    <ul class="nav justify-content-center">
  <li class="nav-item">
    <a class="footer-link" href="#">Sitemap</a>
  </li>
  <li class="nav-item">
    <a class="footer-link" href="#">About</a>
  </li>
  <li class="nav-item">
    <a class="footer-link" href="#">Copyright</a>
  </li>
  <li class="nav-item">
    <a class="footer-link" href="#">Contact</a>
  </li>
</ul>

  </div>
  <div class="footer-copyright mt-3 mb-3">
    © 2021 fdbckr.
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon d-flex">
  <%= link_to root_path, class: "navbar-brand" do %>
    <p class="logo mt-1 mb-1 ml-5 mr-5">fdbckr.</p>
  <% end %>

  <ul class="navbar-nav mr-auto">
    <li class="nav-item active">
      <%= link_to "Home", root_path, class: "nav-link" %>
    </li>
    <li class="nav-item active">
      <%= link_to "Artists", artists_path, class: "nav-link" %>
    </li>
    <li class="nav-item active">
      <%= link_to "Artworks", discover_path, class: "nav-link" %>
    </li>
    <li class="nav-item active">
      <%= link_to "Support", support_path, class: "nav-link" %>
    </li>
  </ul>

  <div class="btn-wrapper-upload">
    <a href="/artworks/new" class="btn-upload">Create a post</a>
    <a href="#" class="btn-shadow-upload">Create a post</a>
  </div>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="full-height">
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item dropdown">
          <% if current_user %>
            <% if current_user.photo.attached? %>
              <%= cl_image_tag current_user.photo.key, width: 40, height: 40, crop: :thumb, gravity: :face, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <% else %>
              <%= image_tag("https://source.unsplash.com/EdAVNRvUVH4/150x150", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false) %>
            <% end %>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
              <%= link_to "Profile", profile_path, class: "dropdown-item" %>
              <%= link_to "Friends", friends_path(current_user), class: "dropdown-item" %>
              <%= link_to "Logout", destroy_user_session_path, method: :delete, class: "dropdown-item"  %>
            </div>
          <% end %>
        </li>
      </ul>
    </div>
  </div>
</div>