config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  match "/404", to: "errors#not_found", via: :all
  match "/500", to: "errors#internal_server_error", via: :all
  root to: 'artworks#index'
  get '/profile', to: 'pages#profile'
  get '/share/:artwork_id', to: 'pages#share', as: 'share'
  post '/mail_request/:artwork_id', to: 'mail_requests#invite_externals', as: 'invite_externals'
  get '/brandguidelines', to: 'pages#brandguidelines'
  get '/landing', to: 'pages#landing'
  get '/users/:id/friends', to: 'users#friends', as: 'friends'
  get '/discover', to: 'artworks#discover'
  get '/artists', to: 'users#index'
  get '/support', to: 'pages#support'
  post '/artworks/:artwork_id/comments/feed', to: 'comments#create_index', as: 'create_comments_index'
  patch 'friendships/:id/accept', to: 'friendships#accept', as: 'accept_friendship'
  patch 'friendships/:id/decline', to: 'friendships#decline', as: 'decline_friendship'
  resources :users, only: :show do
    resources :friendships, only: :create
  end
  resources :artworks, only: [:index, :new, :create, :show] do
    resources :comments, only: [:create]
  end

  get 'card/:id', to: 'comments#card', as: :card

  # Please do NOT delete (it will break the home page)
  # post '/banana', to: 'comments#create_index', as: :create_comments_index
  # ⚠️⚠️⚠️

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/pages/brandguidelines.html.erb
<div class="container">

  <h2 class="mt-3">Logo</h2>
  <p class="logo">fdbckr.</p>

  <h2 class="mt-3">Primary button</h2>
  <a href="#" class="button-primary">Follow</a>

  <h2 class="mt-3">Primary button with Shadow</h2>
  <div class="button-wrapper">
    <a href="#" class="button-primary-shadow">Follow</a>
    <a href="#" class="button-shadow">Follow</a>
  </div>

  <h2 class="mt-3">Secondary button</h2>
  <a href="#" class="button-secondary">Upload your art</a>

  <h2 class="mt-3">Secondary button with shadow</h2>
  <div class="button-wrapper">
    <a href="#" class="button-secondary-shadow">Upload your art</a>
    <a href="#" class="button-shadow">Upload your art</a>
  </div>

  <h2 class="mt-3">Avatar</h2>
  <img class="profile" src="https://source.unsplash.com/0fN7Fxv1eWA/100x100" alt="profile picture">
  <!-- ALTERNATIVE -->
  <!--  <%= image_tag(@artwork.user.avatar, class: 'profile') %> -->

  <h2 class="mt-3">Avatar</h2>
  <img class="profile-home" src="https://source.unsplash.com/0fN7Fxv1eWA/150x150" alt="profile picture">
  <!-- ALTERNATIVE -->
  <!--  <%= image_tag(@artwork.user.avatar, class: 'profile-home') %> -->

  <h2 class="mt-3">Avatar with Notification</h2>
  <div class="profile-image">
  	<a href="#">
		<span class="notify-badge">1</span>
      <img class="profile" src="https://source.unsplash.com/0fN7Fxv1eWA/100x100" alt="profile picture">
        <!-- ALTERNATIVE -->
        <!--  <%= image_tag(@artwork.user.avatar, class: 'profile') %> -->
	  </a>
	</div>

  <h2 class="mt-3">Form</h2>
  <div class="d-flex mt-3">
    <img class="profile mr-3" src="https://source.unsplash.com/0fN7Fxv1eWA/100x100" alt="profile picture">
    <%= simple_form_for [@artwork, @comment], html: { class: 'd-flex flex-column flex-grow-1' } do |f| %>
      <%= f.input :content, input_html: { class: 'flex-grow-1' }, placeholder: 'What would you like to say about this piece?', label: false %>
      <%= f.button :submit, input_html: { class: 'justify-content-center mb-3' } %>
    <% end %>
  </div>

  <h2 class="mt-3">Comment</h2>
  <div class="d-flex mt-3">
    <img class="profile mr-3" src="https://source.unsplash.com/0fN7Fxv1eWA/100x100" alt="profile picture">
      <!-- ALTERNATIVE -->
      <!--  <%= image_tag(@artwork.user.avatar, class: 'profile mr-3') %> -->
    <p class="comment ml-3">For a first digital piece this looks pretty solid. Like a couple of the other comments said, there is definitely way too much use of the texture brushes. The colors are also very vibrant, you could try and experiment with different tints and shades and different colors for shadow. The tree shape also feels a bit artificial, I would recommend using some references to get a more natural look if that makes any sense. overall, very nice for a first digital painting.</p>
  </div>

  <h2 class="mt-3">Centered Content</h2>
  <div class="d-flex justify-content-center">
    <p class="centered-content">I am an artist based in Hamburg and Berlin. I work primarily with lavender and I only collaborate with those that know how to appreciate it. All feedback welcome!</p>
  </div>

  <h2 class="mt-3">Top Description Section</hh2>
  <div class="d-flex mt-5">
    <img class="profile" src="https://source.unsplash.com/0fN7Fxv1eWA/100x100" alt="profile picture">
      <!-- ALTERNATIVE -->
      <!--  <%= image_tag(@artwork.user.avatar, class: 'profile') %> -->
    <div class="container ml-3 top-description">
      <h1>My greatest artwork title</h1>
      <p>@<%= link_to 'martin', "#" %></p>
    </div>
    <div class="button-wrapper">
      <a href="#" class="button-primary-shadow">Follow</a>
      <a href="#" class="button-shadow">Follow</a>
    </div>
  </div>

  <h2 class="mt-3">Navbar</h2>
  
  <div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to root_path, class: "navbar-brand" do %>
    <p class="logo mt-1 mb-1 ml-5 mr-5">fdbckr.</p>
  <% end %>

  <ul class="navbar-nav mr-auto">
    <li class="nav-item active">
      <%= link_to "Home", root_path, class: "nav-link" %>
    </li>
    <li class="nav-item active">
      <%= link_to "Artists", root_path, class: "nav-link" %>
    </li>
    <li class="nav-item active">
      <%= link_to "Artworks", root_path, class: "nav-link" %>
    </li>
    <li class="nav-item active">
      <%= link_to "Support", root_path, class: "nav-link" %>
    </li>
  </ul>

  <div>
    <a href="/artworks/new" class="button-navbar">Upload your art</a>
  </div>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <% if current_user.username =! nil %>
    <div class="full-height">
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item dropdown">
            <%= image_tag (current_user.avatar.nil? ? "https://source.unsplash.com/jZaQOzrC3XU/100x100" : current_user.avatar), class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
              <%= link_to "Action", "#", class: "dropdown-item" %>
              <%= link_to "Another action", "#", class: "dropdown-item" %>
            </div>
          </li>
        </ul>
      </div>
    </div>
    <% end %>
  </div>


  <h2 class="mt-3">Grid</h2>
    <!--Grid row-->
    <div class="row">

      <!--Grid column-->
      <div class="col-lg-4 col-md-6 mb-4">

        <img src="https://source.unsplash.com/xb0wLfZH9Zo/900x600" class="img-fluid mb-4" alt=""
          data-wow-delay="0.1s">

        <img src="https://source.unsplash.com/tKgcMR8saYA/600x900" class="img-fluid mb-4" alt=""
          data-wow-delay="0.4s">

      </div>
      <!--Grid column-->

      <!--Grid column-->
      <div class="col-lg-4 col-md-6 mb-4">

        <img src="https://source.unsplash.com/wN9DU73b8_s/600x900" class="img-fluid mb-4" alt=""
          data-wow-delay="0.2s">

        <img src="https://source.unsplash.com/ineC_oi7NHs/900x600" class="img-fluid mb-4" alt=""
          data-wow-delay="0.5s">

      </div>
      <!--Grid column-->

        <!--Grid column-->
      <div class="col-lg-4 col-md-6 mb-4">

        <img src="https://source.unsplash.com/woMD-vhzOHI/900x600" class="img-fluid mb-4" alt=""
          data-wow-delay="0.1s">

        <img src="https://source.unsplash.com/1rBg5YSi00c/600x900" class="img-fluid mb-4" alt=""
          data-wow-delay="0.4s">

      </div>
      <!--Grid column-->

    </div>
    <!--Grid row-->

  <h2 class="mt-3">End</h2>
</div>

app/views/pages/landing.html.erb
<div class="fullscreen container-fluid">
  <div class="row">
    <div class="col-8">
      <div class="row d-flex align-items-center" id="headline">
        <div class="container">
          <div>
            <h1>Create. Collaborate. Control.</h1>
            <p>Feedbacker offers a new way for artists to create freely, get feedback on their progress and develop the best art they can. </p>
            <div class="button-wrapper">
              <a href="#" class="button-tertiary-shadow">Sign up for free now</a>
              <a href="#" class="button-shadow">Sign up for free now</a>
            </div>
          </div>
        </div>
      </div>
      <div class="row"> 
        <div class="col border-right-landing small-headlines d-flex align-items-end">
          <div>
            <h6>Be in control.</h6>
            <p>You are in charge of the privacy features regarding your work. Decide wheter you want to keep your drafts private or public.</p>
          </div>
        </div>
        <div class="col border-right-landing d-flex align-items-end">
          <div>
            <h6>Find a community.</h6>
            <p>Feedbacker is a collection of like-minded creatives that share the same values and want to progress with their work.</p>
          </div>
        </div>
        <div class="col border-right-landing d-flex align-items-end">
          <div>
            <h6>Progress with your work.</h6>
            <p>Feedback is the best way to learn and progress with your art. You can learn a lot and ultimately create the best version yourself.</p>
          </div>
        </div>
      </div>
    </div>
    <div class="col-4">
      <div class="row">
        <div class="col d-flex align-items-center justify-content-center" id="landing-image">
          <!-- <%= image_tag "landing.jpg", style:'max-height: 90%' %> -->
          <%= cl_image_tag "landing_hnmglg", style:'max-height: 90%' %>  
        </div>
      </div>
      <div class="row">
        <div class="col border-right-landing landing-link text-center d-flex align-items-center justify-content-center">
          <%= link_to  "Log In", root_path%>
        </div>
        <div class="col border-right-landing landing-link d-flex align-items-center justify-content-center">
          <%= link_to  "Sign Up Free", root_path%>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/pages/profile.html.erb
<div class="container mt-5">
  <!-- Content here -->
  <div class="d-flex flex-row bd-highlight mb-3 justify-content-between">
    <div class="d-flex">
      <% if current_user.photo.attached? %>
        <%= cl_image_tag current_user.photo.key, class:"profile-home", height: 300, width: 400, crop: :fill, gravity: "faces" %>
      <% else %>
        <img src="https://source.unsplash.com/EdAVNRvUVH4/150x150" class="profile-home" alt="Profile Picture ">
      <% end %>
      <!-- <img src="https://source.unsplash.com/X6Uj51n5CE8/150x150" class="img-thumbnail" alt="Profile Picture"> -->
    </div>
    <div class="d-flex flex-column bd-highlight flex-grow-1 ml-2">
      <div><h1><i>@<%= current_user.username %></i></h1></div>
      <div>👾 <%= current_user.first_name %> <%= current_user.last_name %></div>
      <div>📍 <%= current_user.location %></div>
    </div>
  </div>

  <div class="d-flex justify-content-center">
    <p class="centered-content"><%= current_user.bio %></p>
  </div>

    <!--Grid row-->
  <div class="grid mt-4">
    <div class="gutter-size"></div>
    <% current_user.artworks.each do |artwork| %>
      <% artwork.photos.each do |photo| %>
        <div class="grid-item">
          <%= cl_image_tag photo.key, class: "w-100" %>

          <a href="<%= artwork_path(artwork) %>" class="hover-img-container-2">
            <div class="overlay">
              <%= artwork.title %>
            </div>
          </a>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/pages/share.html.erb
<div class="share-ctn">
  <div class="info-box">
    <h2 style="margin-top: 80px; font-family: 'Roboto',sans-serif">Congrats, you successfully submitted your work!</h2>
    <div class="justify-content-center mt-4 mb-4">
        <div class="row justify-content-center mt-4">
          <% @artwork.photos.each do |image| %>
            <div class="row img-wrapper">
              <%= cl_image_tag image.key, style: 'max-height: 300px; max-width: 300px; object-fit: cover; border-radius: 4px' %>     
            </div>
          <% end %>
        </div>
      <p class="mt-4">Invite externals to check out your artwork by entering their emails and sending a custom message</p>
    </div>
    <div class="row d-flex align-items-center justify-content-center mt-1">
      <%= simple_form_for :mail_request, url: invite_externals_path(@artwork), html: {class: 'text-left'} do |f| %>
        <select class="emails-input w-100" name="emails[]" multiple="true" id="emails">
        </select>
        <%= f.input :message, label: 'Custom Message', as: :text, label_html: { class: 'text-center w-100 d-block mt-2' } %>
        <div class="optional-invite text-center">
          <%= f.submit "Send Request", class: 'submit-artwork mb-3 row', disabled: true %>
          <a href="<%= artwork_path(@artwork) %>" class="redirect-artwork text-decoration-none row justify-content-center">Back to artwork</a>
        </div>
      <% end %>
    </div>
    
  </div>
</div>

app/views/pages/support.html.erb
<div class="container mt-5">
  <h1 class="center-headers" > Meet your fdbckr Crew </h1>

  <div class="row row-cols-1 row-cols-md-4 g-4">
  <div class="col">
    <div class="card">
      <%= image_tag "yuno.png", class: "card-img-top" %>
      <div class="card-body">
        <h5 class="card-title">Kevin Myung</h5>
        <p class="card-text">kmyung91@gmail.com</p>
      </div>
    </div>
  </div>
  <div class="col">
    <div class="card">
      <%= image_tag "martin.jpeg", class: "card-img-top" %>
      <div class="card-body">
        <h5 class="card-title">Martin Kühne</h5>
        <p class="card-text">martinkuehne@live.de</p>
      </div>
    </div>
  </div>
  <div class="col">
    <div class="card">
      <%= image_tag "Marnie.jpeg", class: "card-img-top" %>
      <div class="card-body">
        <h5 class="card-title">Marnie Nyenhuis</h5>
        <p class="card-text">marnie.nyenhuis@t-online.de</p>
      </div>
    </div>
  </div>
  <div class="col">
    <div class="card">
      <%= image_tag "laura2.jpeg", class: "card-img-top" %>
      <div class="card-body">
        <h5 class="card-title">Laura Hauertmann</h5>
        <p class="card-text">laurahauertmann@gmail.com</p>
      </div>
    </div>
  </div>
</div>


</div>